contentpage={
      LinearLayout;
      orientation="vertical";
      layout_height="fill";
      layout_width="fill";
      background="#ffffffff";

      {
        LinearLayout;
        layout_width="fill";
        layout_height="wrap";
        gravity="center";
        {
          CardView;
          radius="8dp";
          CardBackgroundColor="#fffffff";
          layout_width="95%w";
          layout_margin="6dp";
          id="框一";
          layout_height="18%w";
          elevation="1px";
           layout_marginTop="8dp";
          {
            EditText;
            layout_height="fill";
            textColor="#000000";
            id="note_title";
            textSize="16sp";
            layout_width="fill";
            singleLine=true;
            hint="输入文档标题";
            hintTextColor="#FF9b9b9b";
            background="#E5E1E1E1";
          };
        };
      };
              {
      LinearLayout;
      layout_height="wrap";
      layout_width="fill";
      {
        HorizontalScrollView,
        layout_width="fill";
        layout_height="30dp";
        horizontalScrollBarEnabled=false;
        {
          LinearLayout,
          orientation="horizontal",
          layout_width="fill";
          layout_height="wrap";
          background=backcolor;
          id='sc';
        }
      };
    };

  --[
      {
        LinearLayout;
        layout_width="fill";
        layout_height="wrap";
        gravity="center";
        {
          CardView;
          radius="8dp";
          CardBackgroundColor="#fffffff";
          layout_width="95%w";
          layout_margin="6dp";
          id="框二";
          layout_height="wrap";
          elevation="0dp";
          {
            EditText;
            background="#E5E1E1E1";
            textSize="17sp";
            hint="编辑文章内容";
            layout_width="fill";
            singleLine=false;
            textColor="#000000";
            hintTextColor="#FF9b9b9b";             
            id="note_content";
          };
        };
      };
    --]]
    }
    
    
    
    contentcode={
      LinearLayout;
      orientation="vertical";
      layout_height="fill";
      layout_width="fill";
      background="#ffffffff";
      {
        LinearLayout;
        layout_width="fill";
        layout_height="70dp";
        gravity="center";
        {
          CardView;
          radius="8dp";
          CardBackgroundColor="#fffffff";
          layout_width="95%w";
          id="框一";
          layout_height="12%w";
          elevation="0dp";
          {
            EditText;
            layout_height="fill";
            textColor="#000000";
            id="note_title";
            textSize="15sp";
            layout_width="fill";
            singleLine=true;
            hint="输入文档标题";
            hintTextColor="#FF9b9b9b";
            background="#E5E1E1E1";
          };
        };
      };
    
    
     
     {
      LinearLayout;
      layout_height="3dp";
      layout_width="fill";
      {
        HorizontalScrollView,
        layout_width="fill";
        layout_height="wrap";
        horizontalScrollBarEnabled=false;
        {
          LinearLayout,
          orientation="horizontal",
          layout_width="fill";
          layout_height="70dp";
          background=backcolor;
          id='sc';
        }
      };
    };
    --[
        {
          LinearLayout;
          id="编辑器框架";
          layout_width="fill";
          layout_height="fill";
          {
            LuaEditor;
            layout_weight="0.7";
            layout_width="fill";
             layout_margin="24dp";
            id="note_content";
          };
        };
      --]]
    }
  