postitem=
{


  {
    LinearLayout;
    layout_width="100%w";
    layout_height="-1";
    {
      LinearLayout;
      id="ed";
      --background="#ffffff";
      layout_height="58dp";
      gravity="center";
      layout_margin="4dp";
      layout_width="58dp";
      elevation="0dp";
      {
        CircleImageView;
        layout_margin="10dp";
        layout_height="48dp";
        id="Developer_01";
        layout_gravity="center";
        layout_width="48dp";
        src="icon.png";
      };
    };
    {
      LinearLayout;
      layout_margin="4dp";
      layout_height="-2";
      layout_marginRight="68dp";
      layout_marginTop="2dp";
      layout_width="-2";
      layout_marginBottom="8dp";
      {
        LinearLayout;
        layout_weight="1";
        layout_width="-1";
        orientation="vertical";
        {
          CardView;
          radius=14;
          layout_margin="4dp";
          layout_height="-1";
          background="#FffFFFFB";
          layout_width="-2";
          CardElevation="0";
          {
            LinearLayout;
            orientation="vertical";
            {
              TextView;
              id="username";
              textSize="16sp";
              textColor="#ff58B2DC";
              layout_margin="4dp";
              text="清风明月晓星尘";
            };
            {
              TextView;
              id="usercontent";
              textSize="18sp";
              textColor="#ff080808";
              layout_margin="4dp";
              text=[==[我们生活在阴沟里，但有人依然仰望星空。
怎么样，士道君，四糸乃很酷吧，四糸乃很酷吧]==];
            };
          };
        };
      };
    };
  };



  {
    LinearLayout;
    layout_height="-1";
    gravity="right";
    layout_width="-1";
    {
      LinearLayout;
      layout_height="-2";
      layout_margin="4dp";
      layout_marginBottom="8dp";
      layout_marginTop="2dp";
      layout_width="-2";
      {
        LinearLayout;
        orientation="vertical";
        layout_weight="1";
        layout_marginLeft="74dp";
        layout_width="-1";
        {
          CardView;
          layout_height="-1";
          background="#FffFFFFB";
          layout_margin="4dp";
          radius=14;
          CardElevation="0";
          layout_width="-2";
          {
            LinearLayout;
            orientation="vertical";
            {
              TextView;
              textColor="#ff58B2DC";
              text="清风明月晓星尘";
              layout_gravity="end";
              layout_margin="4dp";
              id="username";
              textSize="16sp";
            };
            {
              TextView;
              textColor="#ff080808";
              text=[==[我们生活在阴沟里，但有人依然仰望星空。
怎么样，士道君，四糸乃很酷吧，四糸乃很酷吧]==];
              layout_margin="4dp";
              id="usercontent";
              textSize="18sp";
            };
          };
        };
      };
    };
    {
      LinearLayout;
      layout_height="58dp";
      gravity="center";
      elevation="0dp";
      id="ed";
      layout_margin="4dp";
      layout_width="58dp";
      {
        CircleImageView;
        layout_height="48dp";
        layout_gravity="center";
        layout_margin="10dp";
        id="Developer_01";
        src="icon.png";
        layout_width="48dp";
      };
    };
  };


  --Type3
  {
    LinearLayout;
    gravity="center";
    orientation="vertical";
    layout_width="-1";
    layout_height="wrap";
    {
      CardView;
      radius=20;
      background="#5066ccff";
      layout_marginBottom="3dp";
      layout_marginTop="3dp";
      layout_height="18dp";
      CardElevation="0";
      {
        TextView;
        id="time";
        textColor="#ff828282";
        layout_margin="2dp";
      };
    };
  };



  {
    LinearLayout;
    layout_height="-1";
    layout_width="-1";
    gravity="right";
    {
      LinearLayout;
      layout_marginLeft="68dp";
      layout_width="-2";
      layout_height="-2";
      layout_marginBottom="8dp";
      layout_marginTop="2dp";
      {
        LinearLayout;
        layout_height="-1";
        orientation="vertical";
        layout_width="-1";
        {
          LinearLayout;
          layout_weight="1";
          layout_width="-1";
          gravity="right";
          {
            CardView;
            radius=14;
            layout_width="-2";
            background="#FffFFFFB";
            layout_margin="4dp";
            layout_height="-1";
            CardElevation="0";
            {
              LinearLayout;
              layout_height="-2";
              layout_width="-1";
              orientation="vertical";
              gravity="right";
              {
                LinearLayout;
                layout_height="-1";
                orientation="vertical";
                layout_width="-1";
                {
                  LinearLayout;
                  layout_height="-2";
                  orientation="vertical";
                  layout_width="-1";
                  {
                    LinearLayout;
                    layout_height="wrap";
                    layout_width="-1";
                    gravity="right|center";
                    {
                      TextView;
                      text="昵称";
                      textColor="#ff888888";
                      textSize="14sp";
                      id="reuser";
                      layout_marginRight="4dp";
                    };
                  };
                  {
                    TextView;
                    text="内容";
                    textColor="#ff777777";
                    id="recontent";
                    layout_margin="8dp";
                  };
                };
              };
              {
                LinearLayout;
                layout_height="-1";
                orientation="vertical";
                layout_width="-1";
                {
                  TextView;
                  text="清风明月晓星尘";
                  layout_gravity="end";
                  layout_margin="4dp";
                  textSize="16sp";
                  id="username";
                  textColor="#ff58B2DC";
                };
                {
                  TextView;
                  text=[==[我们生活在阴沟里，但有人依然仰望星空。
怎么样，士道君，四糸乃很酷吧，四糸乃很酷吧]==];
                  layout_margin="4dp";
                  textSize="18sp";
                  id="usercontent";
                  textColor="#ff080808";
                };
              };
            };
          };
        };
      };
    };
    {
      LinearLayout;
      layout_width="58dp";
      elevation="0dp";
      layout_margin="4dp";
      layout_height="58dp";
      id="ed";
      gravity="center";
      {
        CircleImageView;
        layout_width="48dp";
        layout_gravity="center";
        layout_margin="10dp";
        layout_height="48dp";
        id="Developer_01";
        src="icon.png";
      };
    };
  };

}



--[[
  --type4
  {--report
    LinearLayout;
    gravity="right";
    layout_width="-1";
    layout_height="-1";
    {
      LinearLayout;
      layout_width="-2",
      layout_height="-2";
      layout_marginLeft="68dp";
      layout_marginTop="2dp";
      layout_marginBottom="8dp";
      {
        LinearLayout;
        layout_width="-1",
        layout_height="-1";
        orientation="vertical";
        {
          LinearLayout;
          layout_width="-1",
          layout_height="26dp";
          gravity="right|center";
          {
            TextView;
            id="username";
            text="昵称";
            textSize="14sp";
            layout_marginRight="4dp";
            textColor="#ff444444";
          };
          {
            CardView;
            layout_marginTop="3dp";
            layout_marginBottom="3dp";
            radius=20;
            CardElevation="0";
            background="#5066ccff";
            layout_height="18dp";
            {
              LinearLayout;
              layout_width="-1";
              layout_height="-1";
              gravity="center";
              {
                TextView;
                text="最强群主";
                textSize="10sp";
                layout_marginLeft="4dp";
                layout_marginRight="4dp";
              };
            };
          };
        };
        {
          LinearLayout;
          layout_width="-1";
          layout_weight="1";
          gravity="right";
          {
            CardView;
            layout_width="-2";
            layout_height="-1";
            layout_margin="2dp";
            radius=0;
            {
              LinearLayout;
              layout_width="-1";
              layout_height="-1";
              orientation="vertical";
              {
                LinearLayout;
                layout_width="-1";
                layout_height="-2";
                gravity="right";
                {
                  CardView;
                  layout_width="-2";
                  layout_height="-1";
                  layout_margin="6dp";
                  {
                    LinearLayout;
                    layout_width="-1",
                    layout_height="-2";
                    orientation="vertical";
                    {
                      LinearLayout;
                      layout_width="-1",
                      layout_height="26dp";
                      gravity="right|center";
                      {
                        TextView;
                        id="reuser";
                        text="昵称";
                        textSize="14sp";
                        layout_marginRight="4dp";
                        textColor="#ff888888";
                      };
                      {
                        CardView;
                        layout_marginTop="3dp";
                        layout_marginBottom="3dp";
                        layout_marginRight="4dp";
                        radius=20;
                        CardElevation="0";
                        background="#5066ccff";
                        layout_height="18dp";
                        {
                          LinearLayout;
                          layout_width="-1";
                          layout_height="-1";
                          gravity="center";
                          {
                            TextView;
                            text="最吊群员";
                            textSize="10sp";
                            layout_marginLeft="4dp";
                            layout_marginRight="4dp";
                          };
                        };
                      };
                    };
                    {
                      LinearLayout;
                      layout_width="-1";
                      layout_weight="1";
                      gravity="right";
                      {
                        TextView;
                        id="recontent";
                        text="内容";
                        textColor="#ff777777";
                        layout_margin="8dp";
                      };
                    };
                  };
                };
              };
              {
                TextView;
                id="usercontent";
                text="内容";
                textColor="#ff000000";
                layout_margin="8dp";
                layout_width="-1";
                gravity="right";
                layout_height="-2";
              };
            };
          };
        };
      };
    };
    {
      LinearLayout;
      id="ed";
      layout_width="50dp";
      layout_height="50dp";
      elevation="2dp";
      layout_margin="4dp";
      background="#ffffff";
      gravity="center";
      {
        ImageView;
        src="tx.jpg";
        layout_width="-1";
        layout_height="-1";
      };
    };
  };
]]

--[[
--仿tgtype1
        {
        LinearLayout;
        layout_width="100%w";
        layout_height="-1";
          {
          LinearLayout;
          id="ed";
          elevation="0dp";
          layout_height="58dp";
          layout_width="58dp";
          layout_margin="4dp";
          gravity="center";
          background="#ffffff";
            {
            CircleImageView;
            layout_margin="10dp";
            layout_height="48dp";
            src="icon.png";
            layout_gravity="center";
            layout_width="48dp";
            id="Developer_01";
        };
            };
            {
            LinearLayout;
            layout_margin="4dp";
            layout_height="-2";
            layout_marginRight="68dp";
            layout_marginTop="2dp";
            layout_width="-2";
            layout_marginBottom="8dp";
                {
                LinearLayout;
                layout_weight="1";
                layout_width="-1";
                orientation="vertical";
                    {
                    CardView;
                    radius=14;
                    layout_margin="4dp";
                    layout_height="-1";
                    background="#ff434343";
                    layout_width="-2";
                    CardElevation="0";
                        {
                        LinearLayout;
                        orientation="vertical";
                            {
                            TextView;
                            id="username";
                            textSize="16sp";
                            textColor="#ff58B2DC";
                            layout_margin="4dp";
                            text="清风明月晓星尘";
                            };
                            {
                            TextView;
                            id="usercontent";
                            textSize="20sp";
                            textColor="#FffFFFFB";
                            layout_margin="8dp";
                            text=[==[我们生活在阴沟里，但有人依然仰望星空。
怎么样，士道君，四糸乃很酷吧，四糸乃很酷吧]==];
                    };
                };
            };
        };
    };
    };


]]